// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ClientResponseData, unionToClientResponseData, unionListToClientResponseData } from '../exchange/client-response-data.js';
import { OrderResponse, OrderResponseT } from '../exchange/order-response.js';
import { PositionResponse, PositionResponseT } from '../exchange/position-response.js';


export class ClientResponse implements flatbuffers.IUnpackableObject<ClientResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClientResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClientResponse(bb:flatbuffers.ByteBuffer, obj?:ClientResponse):ClientResponse {
  return (obj || new ClientResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClientResponse(bb:flatbuffers.ByteBuffer, obj?:ClientResponse):ClientResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

dataType():ClientResponseData {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ClientResponseData.NONE;
}

data<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startClientResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDataType(builder:flatbuffers.Builder, dataType:ClientResponseData) {
  builder.addFieldInt8(0, dataType, ClientResponseData.NONE);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
}

static endClientResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClientResponse(builder:flatbuffers.Builder, dataType:ClientResponseData, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientResponse.startClientResponse(builder);
  ClientResponse.addDataType(builder, dataType);
  ClientResponse.addData(builder, dataOffset);
  return ClientResponse.endClientResponse(builder);
}

unpack(): ClientResponseT {
  return new ClientResponseT(
    this.dataType(),
    (() => {
      const temp = unionToClientResponseData(this.dataType(), this.data.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: ClientResponseT): void {
  _o.dataType = this.dataType();
  _o.data = (() => {
      const temp = unionToClientResponseData(this.dataType(), this.data.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class ClientResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public dataType: ClientResponseData = ClientResponseData.NONE,
  public data: OrderResponseT|PositionResponseT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const data = builder.createObjectOffset(this.data);

  return ClientResponse.createClientResponse(builder,
    this.dataType,
    data
  );
}
}
