// automatically generated by the FlatBuffers compiler, do not modify

import { OrderResponse } from '../exchange/order-response.js';
import { PositionResponse } from '../exchange/position-response.js';


export enum ClientResponseData {
  NONE = 0,
  OrderResponse = 1,
  PositionResponse = 2
}

export function unionToClientResponseData(
  type: ClientResponseData,
  accessor: (obj:OrderResponse|PositionResponse) => OrderResponse|PositionResponse|null
): OrderResponse|PositionResponse|null {
  switch(ClientResponseData[type]) {
    case 'NONE': return null; 
    case 'OrderResponse': return accessor(new OrderResponse())! as OrderResponse;
    case 'PositionResponse': return accessor(new PositionResponse())! as PositionResponse;
    default: return null;
  }
}

export function unionListToClientResponseData(
  type: ClientResponseData, 
  accessor: (index: number, obj:OrderResponse|PositionResponse) => OrderResponse|PositionResponse|null, 
  index: number
): OrderResponse|PositionResponse|null {
  switch(ClientResponseData[type]) {
    case 'NONE': return null; 
    case 'OrderResponse': return accessor(index, new OrderResponse())! as OrderResponse;
    case 'PositionResponse': return accessor(index, new PositionResponse())! as PositionResponse;
    default: return null;
  }
}
