// automatically generated by the FlatBuffers compiler, do not modify

import { OrderRequest } from '../exchange/order-request.js';
import { OrderStatusRequest } from '../exchange/order-status-request.js';
import { PositionRequest } from '../exchange/position-request.js';


export enum ClientRequestData {
  NONE = 0,
  OrderRequest = 1,
  PositionRequest = 2,
  OrderStatusRequest = 3
}

export function unionToClientRequestData(
  type: ClientRequestData,
  accessor: (obj:OrderRequest|OrderStatusRequest|PositionRequest) => OrderRequest|OrderStatusRequest|PositionRequest|null
): OrderRequest|OrderStatusRequest|PositionRequest|null {
  switch(ClientRequestData[type]) {
    case 'NONE': return null; 
    case 'OrderRequest': return accessor(new OrderRequest())! as OrderRequest;
    case 'PositionRequest': return accessor(new PositionRequest())! as PositionRequest;
    case 'OrderStatusRequest': return accessor(new OrderStatusRequest())! as OrderStatusRequest;
    default: return null;
  }
}

export function unionListToClientRequestData(
  type: ClientRequestData, 
  accessor: (index: number, obj:OrderRequest|OrderStatusRequest|PositionRequest) => OrderRequest|OrderStatusRequest|PositionRequest|null, 
  index: number
): OrderRequest|OrderStatusRequest|PositionRequest|null {
  switch(ClientRequestData[type]) {
    case 'NONE': return null; 
    case 'OrderRequest': return accessor(index, new OrderRequest())! as OrderRequest;
    case 'PositionRequest': return accessor(index, new PositionRequest())! as PositionRequest;
    case 'OrderStatusRequest': return accessor(index, new OrderStatusRequest())! as OrderStatusRequest;
    default: return null;
  }
}
