// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ClientRequestData, unionToClientRequestData, unionListToClientRequestData } from '../exchange/client-request-data.js';
import { OrderRequest, OrderRequestT } from '../exchange/order-request.js';
import { OrderStatusRequest, OrderStatusRequestT } from '../exchange/order-status-request.js';
import { PositionRequest, PositionRequestT } from '../exchange/position-request.js';


export class ClientRequest implements flatbuffers.IUnpackableObject<ClientRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClientRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClientRequest(bb:flatbuffers.ByteBuffer, obj?:ClientRequest):ClientRequest {
  return (obj || new ClientRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClientRequest(bb:flatbuffers.ByteBuffer, obj?:ClientRequest):ClientRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

dataType():ClientRequestData {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ClientRequestData.NONE;
}

data<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startClientRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDataType(builder:flatbuffers.Builder, dataType:ClientRequestData) {
  builder.addFieldInt8(0, dataType, ClientRequestData.NONE);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
}

static endClientRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClientRequest(builder:flatbuffers.Builder, dataType:ClientRequestData, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientRequest.startClientRequest(builder);
  ClientRequest.addDataType(builder, dataType);
  ClientRequest.addData(builder, dataOffset);
  return ClientRequest.endClientRequest(builder);
}

unpack(): ClientRequestT {
  return new ClientRequestT(
    this.dataType(),
    (() => {
      const temp = unionToClientRequestData(this.dataType(), this.data.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: ClientRequestT): void {
  _o.dataType = this.dataType();
  _o.data = (() => {
      const temp = unionToClientRequestData(this.dataType(), this.data.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class ClientRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public dataType: ClientRequestData = ClientRequestData.NONE,
  public data: OrderRequestT|OrderStatusRequestT|PositionRequestT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const data = builder.createObjectOffset(this.data);

  return ClientRequest.createClientRequest(builder,
    this.dataType,
    data
  );
}
}
