// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ClientResponseData, unionToClientResponseData, unionListToClientResponseData } from '../exchange/client-response-data.js';


export class ClientResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClientResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClientResponse(bb:flatbuffers.ByteBuffer, obj?:ClientResponse):ClientResponse {
  return (obj || new ClientResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClientResponse(bb:flatbuffers.ByteBuffer, obj?:ClientResponse):ClientResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

dataType():ClientResponseData {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ClientResponseData.NONE;
}

data<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startClientResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDataType(builder:flatbuffers.Builder, dataType:ClientResponseData) {
  builder.addFieldInt8(0, dataType, ClientResponseData.NONE);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
}

static endClientResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClientResponse(builder:flatbuffers.Builder, dataType:ClientResponseData, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientResponse.startClientResponse(builder);
  ClientResponse.addDataType(builder, dataType);
  ClientResponse.addData(builder, dataOffset);
  return ClientResponse.endClientResponse(builder);
}
}
