// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { L2Update, L2UpdateT } from '../exchange/l2-update.js';


export class L2Batch implements flatbuffers.IUnpackableObject<L2BatchT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):L2Batch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsL2Batch(bb:flatbuffers.ByteBuffer, obj?:L2Batch):L2Batch {
  return (obj || new L2Batch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsL2Batch(bb:flatbuffers.ByteBuffer, obj?:L2Batch):L2Batch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new L2Batch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

seqNum():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

updates(index: number, obj?:L2Update):L2Update|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new L2Update()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

updatesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startL2Batch(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSeqNum(builder:flatbuffers.Builder, seqNum:bigint) {
  builder.addFieldInt64(0, seqNum, BigInt('0'));
}

static addUpdates(builder:flatbuffers.Builder, updatesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, updatesOffset, 0);
}

static createUpdatesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startUpdatesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endL2Batch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createL2Batch(builder:flatbuffers.Builder, seqNum:bigint, updatesOffset:flatbuffers.Offset):flatbuffers.Offset {
  L2Batch.startL2Batch(builder);
  L2Batch.addSeqNum(builder, seqNum);
  L2Batch.addUpdates(builder, updatesOffset);
  return L2Batch.endL2Batch(builder);
}

unpack(): L2BatchT {
  return new L2BatchT(
    this.seqNum(),
    this.bb!.createObjList<L2Update, L2UpdateT>(this.updates.bind(this), this.updatesLength())
  );
}


unpackTo(_o: L2BatchT): void {
  _o.seqNum = this.seqNum();
  _o.updates = this.bb!.createObjList<L2Update, L2UpdateT>(this.updates.bind(this), this.updatesLength());
}
}

export class L2BatchT implements flatbuffers.IGeneratedObject {
constructor(
  public seqNum: bigint = BigInt('0'),
  public updates: (L2UpdateT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const updates = L2Batch.createUpdatesVector(builder, builder.createObjectOffsetList(this.updates));

  return L2Batch.createL2Batch(builder,
    this.seqNum,
    updates
  );
}
}
