// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Side } from '../exchange/side.js';


export class L2Update {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):L2Update {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsL2Update(bb:flatbuffers.ByteBuffer, obj?:L2Update):L2Update {
  return (obj || new L2Update()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsL2Update(bb:flatbuffers.ByteBuffer, obj?:L2Update):L2Update {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new L2Update()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

symbolId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

seqNum():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

side():Side {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : Side.Buy;
}

p():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

q():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startL2Update(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addSymbolId(builder:flatbuffers.Builder, symbolId:number) {
  builder.addFieldInt32(0, symbolId, 0);
}

static addSeqNum(builder:flatbuffers.Builder, seqNum:bigint) {
  builder.addFieldInt64(1, seqNum, BigInt('0'));
}

static addSide(builder:flatbuffers.Builder, side:Side) {
  builder.addFieldInt8(2, side, Side.Buy);
}

static addP(builder:flatbuffers.Builder, p:bigint) {
  builder.addFieldInt64(3, p, BigInt('0'));
}

static addQ(builder:flatbuffers.Builder, q:bigint) {
  builder.addFieldInt64(4, q, BigInt('0'));
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(5, timestamp, BigInt('0'));
}

static endL2Update(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createL2Update(builder:flatbuffers.Builder, symbolId:number, seqNum:bigint, side:Side, p:bigint, q:bigint, timestamp:bigint):flatbuffers.Offset {
  L2Update.startL2Update(builder);
  L2Update.addSymbolId(builder, symbolId);
  L2Update.addSeqNum(builder, seqNum);
  L2Update.addSide(builder, side);
  L2Update.addP(builder, p);
  L2Update.addQ(builder, q);
  L2Update.addTimestamp(builder, timestamp);
  return L2Update.endL2Update(builder);
}
}
