// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { L3Update, L3UpdateT } from '../exchange/l3-update.js';


export class L3Batch implements flatbuffers.IUnpackableObject<L3BatchT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):L3Batch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsL3Batch(bb:flatbuffers.ByteBuffer, obj?:L3Batch):L3Batch {
  return (obj || new L3Batch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsL3Batch(bb:flatbuffers.ByteBuffer, obj?:L3Batch):L3Batch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new L3Batch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

seqNum():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

updates(index: number, obj?:L3Update):L3Update|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new L3Update()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

updatesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startL3Batch(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSeqNum(builder:flatbuffers.Builder, seqNum:bigint) {
  builder.addFieldInt64(0, seqNum, BigInt('0'));
}

static addUpdates(builder:flatbuffers.Builder, updatesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, updatesOffset, 0);
}

static createUpdatesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startUpdatesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endL3Batch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishL3BatchBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedL3BatchBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createL3Batch(builder:flatbuffers.Builder, seqNum:bigint, updatesOffset:flatbuffers.Offset):flatbuffers.Offset {
  L3Batch.startL3Batch(builder);
  L3Batch.addSeqNum(builder, seqNum);
  L3Batch.addUpdates(builder, updatesOffset);
  return L3Batch.endL3Batch(builder);
}

unpack(): L3BatchT {
  return new L3BatchT(
    this.seqNum(),
    this.bb!.createObjList<L3Update, L3UpdateT>(this.updates.bind(this), this.updatesLength())
  );
}


unpackTo(_o: L3BatchT): void {
  _o.seqNum = this.seqNum();
  _o.updates = this.bb!.createObjList<L3Update, L3UpdateT>(this.updates.bind(this), this.updatesLength());
}
}

export class L3BatchT implements flatbuffers.IGeneratedObject {
constructor(
  public seqNum: bigint = BigInt('0'),
  public updates: (L3UpdateT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const updates = L3Batch.createUpdatesVector(builder, builder.createObjectOffsetList(this.updates));

  return L3Batch.createL3Batch(builder,
    this.seqNum,
    updates
  );
}
}
