// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ExecType } from '../exchange/exec-type.js';
import { Side } from '../exchange/side.js';


export class L3Update implements flatbuffers.IUnpackableObject<L3UpdateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):L3Update {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsL3Update(bb:flatbuffers.ByteBuffer, obj?:L3Update):L3Update {
  return (obj || new L3Update()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsL3Update(bb:flatbuffers.ByteBuffer, obj?:L3Update):L3Update {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new L3Update()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

symbolId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

execType():ExecType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ExecType.New;
}

seqNum():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

orderId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

side():Side {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : Side.Buy;
}

p():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

q():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startL3Update(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addSymbolId(builder:flatbuffers.Builder, symbolId:number) {
  builder.addFieldInt32(0, symbolId, 0);
}

static addExecType(builder:flatbuffers.Builder, execType:ExecType) {
  builder.addFieldInt8(1, execType, ExecType.New);
}

static addSeqNum(builder:flatbuffers.Builder, seqNum:bigint) {
  builder.addFieldInt64(2, seqNum, BigInt('0'));
}

static addOrderId(builder:flatbuffers.Builder, orderId:bigint) {
  builder.addFieldInt64(3, orderId, BigInt('0'));
}

static addSide(builder:flatbuffers.Builder, side:Side) {
  builder.addFieldInt8(4, side, Side.Buy);
}

static addP(builder:flatbuffers.Builder, p:bigint) {
  builder.addFieldInt64(5, p, BigInt('0'));
}

static addQ(builder:flatbuffers.Builder, q:bigint) {
  builder.addFieldInt64(6, q, BigInt('0'));
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(7, timestamp, BigInt('0'));
}

static endL3Update(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createL3Update(builder:flatbuffers.Builder, symbolId:number, execType:ExecType, seqNum:bigint, orderId:bigint, side:Side, p:bigint, q:bigint, timestamp:bigint):flatbuffers.Offset {
  L3Update.startL3Update(builder);
  L3Update.addSymbolId(builder, symbolId);
  L3Update.addExecType(builder, execType);
  L3Update.addSeqNum(builder, seqNum);
  L3Update.addOrderId(builder, orderId);
  L3Update.addSide(builder, side);
  L3Update.addP(builder, p);
  L3Update.addQ(builder, q);
  L3Update.addTimestamp(builder, timestamp);
  return L3Update.endL3Update(builder);
}

unpack(): L3UpdateT {
  return new L3UpdateT(
    this.symbolId(),
    this.execType(),
    this.seqNum(),
    this.orderId(),
    this.side(),
    this.p(),
    this.q(),
    this.timestamp()
  );
}


unpackTo(_o: L3UpdateT): void {
  _o.symbolId = this.symbolId();
  _o.execType = this.execType();
  _o.seqNum = this.seqNum();
  _o.orderId = this.orderId();
  _o.side = this.side();
  _o.p = this.p();
  _o.q = this.q();
  _o.timestamp = this.timestamp();
}
}

export class L3UpdateT implements flatbuffers.IGeneratedObject {
constructor(
  public symbolId: number = 0,
  public execType: ExecType = ExecType.New,
  public seqNum: bigint = BigInt('0'),
  public orderId: bigint = BigInt('0'),
  public side: Side = Side.Buy,
  public p: bigint = BigInt('0'),
  public q: bigint = BigInt('0'),
  public timestamp: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return L3Update.createL3Update(builder,
    this.symbolId,
    this.execType,
    this.seqNum,
    this.orderId,
    this.side,
    this.p,
    this.q,
    this.timestamp
  );
}
}
