// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { OrderAction } from '../exchange/order-action.js';
import { OrderType } from '../exchange/order-type.js';
import { Side } from '../exchange/side.js';


export class OrderRequest implements flatbuffers.IUnpackableObject<OrderRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OrderRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOrderRequest(bb:flatbuffers.ByteBuffer, obj?:OrderRequest):OrderRequest {
  return (obj || new OrderRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOrderRequest(bb:flatbuffers.ByteBuffer, obj?:OrderRequest):OrderRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OrderRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

action():OrderAction {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : OrderAction.New;
}

execId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

orderId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

clientId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

symbolId():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

side():Side {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : Side.Buy;
}

type():OrderType {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : OrderType.Limit;
}

p():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

q():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

visibleQty():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startOrderRequest(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addAction(builder:flatbuffers.Builder, action:OrderAction) {
  builder.addFieldInt8(0, action, OrderAction.New);
}

static addExecId(builder:flatbuffers.Builder, execId:bigint) {
  builder.addFieldInt64(1, execId, BigInt('0'));
}

static addOrderId(builder:flatbuffers.Builder, orderId:bigint) {
  builder.addFieldInt64(2, orderId, BigInt('0'));
}

static addClientId(builder:flatbuffers.Builder, clientId:number) {
  builder.addFieldInt32(3, clientId, 0);
}

static addSymbolId(builder:flatbuffers.Builder, symbolId:number) {
  builder.addFieldInt32(4, symbolId, 0);
}

static addSide(builder:flatbuffers.Builder, side:Side) {
  builder.addFieldInt8(5, side, Side.Buy);
}

static addType(builder:flatbuffers.Builder, type:OrderType) {
  builder.addFieldInt8(6, type, OrderType.Limit);
}

static addP(builder:flatbuffers.Builder, p:bigint) {
  builder.addFieldInt64(7, p, BigInt('0'));
}

static addQ(builder:flatbuffers.Builder, q:bigint) {
  builder.addFieldInt64(8, q, BigInt('0'));
}

static addVisibleQty(builder:flatbuffers.Builder, visibleQty:bigint) {
  builder.addFieldInt64(9, visibleQty, BigInt('0'));
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(10, timestamp, BigInt('0'));
}

static endOrderRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOrderRequest(builder:flatbuffers.Builder, action:OrderAction, execId:bigint, orderId:bigint, clientId:number, symbolId:number, side:Side, type:OrderType, p:bigint, q:bigint, visibleQty:bigint, timestamp:bigint):flatbuffers.Offset {
  OrderRequest.startOrderRequest(builder);
  OrderRequest.addAction(builder, action);
  OrderRequest.addExecId(builder, execId);
  OrderRequest.addOrderId(builder, orderId);
  OrderRequest.addClientId(builder, clientId);
  OrderRequest.addSymbolId(builder, symbolId);
  OrderRequest.addSide(builder, side);
  OrderRequest.addType(builder, type);
  OrderRequest.addP(builder, p);
  OrderRequest.addQ(builder, q);
  OrderRequest.addVisibleQty(builder, visibleQty);
  OrderRequest.addTimestamp(builder, timestamp);
  return OrderRequest.endOrderRequest(builder);
}

unpack(): OrderRequestT {
  return new OrderRequestT(
    this.action(),
    this.execId(),
    this.orderId(),
    this.clientId(),
    this.symbolId(),
    this.side(),
    this.type(),
    this.p(),
    this.q(),
    this.visibleQty(),
    this.timestamp()
  );
}


unpackTo(_o: OrderRequestT): void {
  _o.action = this.action();
  _o.execId = this.execId();
  _o.orderId = this.orderId();
  _o.clientId = this.clientId();
  _o.symbolId = this.symbolId();
  _o.side = this.side();
  _o.type = this.type();
  _o.p = this.p();
  _o.q = this.q();
  _o.visibleQty = this.visibleQty();
  _o.timestamp = this.timestamp();
}
}

export class OrderRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public action: OrderAction = OrderAction.New,
  public execId: bigint = BigInt('0'),
  public orderId: bigint = BigInt('0'),
  public clientId: number = 0,
  public symbolId: number = 0,
  public side: Side = Side.Buy,
  public type: OrderType = OrderType.Limit,
  public p: bigint = BigInt('0'),
  public q: bigint = BigInt('0'),
  public visibleQty: bigint = BigInt('0'),
  public timestamp: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return OrderRequest.createOrderRequest(builder,
    this.action,
    this.execId,
    this.orderId,
    this.clientId,
    this.symbolId,
    this.side,
    this.type,
    this.p,
    this.q,
    this.visibleQty,
    this.timestamp
  );
}
}
