// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ExecType } from '../exchange/exec-type.js';
import { RejectCode } from '../exchange/reject-code.js';
import { Side } from '../exchange/side.js';


export class OrderResponse implements flatbuffers.IUnpackableObject<OrderResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OrderResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOrderResponse(bb:flatbuffers.ByteBuffer, obj?:OrderResponse):OrderResponse {
  return (obj || new OrderResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOrderResponse(bb:flatbuffers.ByteBuffer, obj?:OrderResponse):OrderResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OrderResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

execType():ExecType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ExecType.New;
}

orderId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

clientId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

execId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

symbolId():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

side():Side {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : Side.Buy;
}

p():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

q():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

rejectCode():RejectCode {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : RejectCode.None;
}

static startOrderResponse(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addExecType(builder:flatbuffers.Builder, execType:ExecType) {
  builder.addFieldInt8(0, execType, ExecType.New);
}

static addOrderId(builder:flatbuffers.Builder, orderId:bigint) {
  builder.addFieldInt64(1, orderId, BigInt('0'));
}

static addClientId(builder:flatbuffers.Builder, clientId:number) {
  builder.addFieldInt32(2, clientId, 0);
}

static addExecId(builder:flatbuffers.Builder, execId:bigint) {
  builder.addFieldInt64(3, execId, BigInt('0'));
}

static addSymbolId(builder:flatbuffers.Builder, symbolId:number) {
  builder.addFieldInt32(4, symbolId, 0);
}

static addSide(builder:flatbuffers.Builder, side:Side) {
  builder.addFieldInt8(5, side, Side.Buy);
}

static addP(builder:flatbuffers.Builder, p:bigint) {
  builder.addFieldInt64(6, p, BigInt('0'));
}

static addQ(builder:flatbuffers.Builder, q:bigint) {
  builder.addFieldInt64(7, q, BigInt('0'));
}

static addRejectCode(builder:flatbuffers.Builder, rejectCode:RejectCode) {
  builder.addFieldInt8(8, rejectCode, RejectCode.None);
}

static endOrderResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOrderResponse(builder:flatbuffers.Builder, execType:ExecType, orderId:bigint, clientId:number, execId:bigint, symbolId:number, side:Side, p:bigint, q:bigint, rejectCode:RejectCode):flatbuffers.Offset {
  OrderResponse.startOrderResponse(builder);
  OrderResponse.addExecType(builder, execType);
  OrderResponse.addOrderId(builder, orderId);
  OrderResponse.addClientId(builder, clientId);
  OrderResponse.addExecId(builder, execId);
  OrderResponse.addSymbolId(builder, symbolId);
  OrderResponse.addSide(builder, side);
  OrderResponse.addP(builder, p);
  OrderResponse.addQ(builder, q);
  OrderResponse.addRejectCode(builder, rejectCode);
  return OrderResponse.endOrderResponse(builder);
}

unpack(): OrderResponseT {
  return new OrderResponseT(
    this.execType(),
    this.orderId(),
    this.clientId(),
    this.execId(),
    this.symbolId(),
    this.side(),
    this.p(),
    this.q(),
    this.rejectCode()
  );
}


unpackTo(_o: OrderResponseT): void {
  _o.execType = this.execType();
  _o.orderId = this.orderId();
  _o.clientId = this.clientId();
  _o.execId = this.execId();
  _o.symbolId = this.symbolId();
  _o.side = this.side();
  _o.p = this.p();
  _o.q = this.q();
  _o.rejectCode = this.rejectCode();
}
}

export class OrderResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public execType: ExecType = ExecType.New,
  public orderId: bigint = BigInt('0'),
  public clientId: number = 0,
  public execId: bigint = BigInt('0'),
  public symbolId: number = 0,
  public side: Side = Side.Buy,
  public p: bigint = BigInt('0'),
  public q: bigint = BigInt('0'),
  public rejectCode: RejectCode = RejectCode.None
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return OrderResponse.createOrderResponse(builder,
    this.execType,
    this.orderId,
    this.clientId,
    this.execId,
    this.symbolId,
    this.side,
    this.p,
    this.q,
    this.rejectCode
  );
}
}
