// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class OrderStatusRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OrderStatusRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOrderStatusRequest(bb:flatbuffers.ByteBuffer, obj?:OrderStatusRequest):OrderStatusRequest {
  return (obj || new OrderStatusRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOrderStatusRequest(bb:flatbuffers.ByteBuffer, obj?:OrderStatusRequest):OrderStatusRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OrderStatusRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

orderId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startOrderStatusRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addClientId(builder:flatbuffers.Builder, clientId:number) {
  builder.addFieldInt32(0, clientId, 0);
}

static addOrderId(builder:flatbuffers.Builder, orderId:bigint) {
  builder.addFieldInt64(1, orderId, BigInt('0'));
}

static endOrderStatusRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOrderStatusRequest(builder:flatbuffers.Builder, clientId:number, orderId:bigint):flatbuffers.Offset {
  OrderStatusRequest.startOrderStatusRequest(builder);
  OrderStatusRequest.addClientId(builder, clientId);
  OrderStatusRequest.addOrderId(builder, orderId);
  return OrderStatusRequest.endOrderStatusRequest(builder);
}
}
