// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class PositionResponse implements flatbuffers.IUnpackableObject<PositionResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PositionResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPositionResponse(bb:flatbuffers.ByteBuffer, obj?:PositionResponse):PositionResponse {
  return (obj || new PositionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPositionResponse(bb:flatbuffers.ByteBuffer, obj?:PositionResponse):PositionResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PositionResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

symbolId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

position():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startPositionResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addClientId(builder:flatbuffers.Builder, clientId:number) {
  builder.addFieldInt32(0, clientId, 0);
}

static addSymbolId(builder:flatbuffers.Builder, symbolId:number) {
  builder.addFieldInt32(1, symbolId, 0);
}

static addPosition(builder:flatbuffers.Builder, position:bigint) {
  builder.addFieldInt64(2, position, BigInt('0'));
}

static endPositionResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPositionResponse(builder:flatbuffers.Builder, clientId:number, symbolId:number, position:bigint):flatbuffers.Offset {
  PositionResponse.startPositionResponse(builder);
  PositionResponse.addClientId(builder, clientId);
  PositionResponse.addSymbolId(builder, symbolId);
  PositionResponse.addPosition(builder, position);
  return PositionResponse.endPositionResponse(builder);
}

unpack(): PositionResponseT {
  return new PositionResponseT(
    this.clientId(),
    this.symbolId(),
    this.position()
  );
}


unpackTo(_o: PositionResponseT): void {
  _o.clientId = this.clientId();
  _o.symbolId = this.symbolId();
  _o.position = this.position();
}
}

export class PositionResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public clientId: number = 0,
  public symbolId: number = 0,
  public position: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return PositionResponse.createPositionResponse(builder,
    this.clientId,
    this.symbolId,
    this.position
  );
}
}
