// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class PositionRequest implements flatbuffers.IUnpackableObject<PositionRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PositionRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPositionRequest(bb:flatbuffers.ByteBuffer, obj?:PositionRequest):PositionRequest {
  return (obj || new PositionRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPositionRequest(bb:flatbuffers.ByteBuffer, obj?:PositionRequest):PositionRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PositionRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

symbolId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startPositionRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addClientId(builder:flatbuffers.Builder, clientId:number) {
  builder.addFieldInt32(0, clientId, 0);
}

static addSymbolId(builder:flatbuffers.Builder, symbolId:number) {
  builder.addFieldInt32(1, symbolId, 0);
}

static endPositionRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPositionRequest(builder:flatbuffers.Builder, clientId:number, symbolId:number):flatbuffers.Offset {
  PositionRequest.startPositionRequest(builder);
  PositionRequest.addClientId(builder, clientId);
  PositionRequest.addSymbolId(builder, symbolId);
  return PositionRequest.endPositionRequest(builder);
}

unpack(): PositionRequestT {
  return new PositionRequestT(
    this.clientId(),
    this.symbolId()
  );
}


unpackTo(_o: PositionRequestT): void {
  _o.clientId = this.clientId();
  _o.symbolId = this.symbolId();
}
}

export class PositionRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public clientId: number = 0,
  public symbolId: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return PositionRequest.createPositionRequest(builder,
    this.clientId,
    this.symbolId
  );
}
}
