// automatically generated by the FlatBuffers compiler, do not modify

export enum RejectCode {
  Unknown = -1,
  None = 0,
  PriceInvalid = 1,
  OrderNotFound = 2,
  InvalidAction = 3,
  InvalidModify = 4
}
